version: '3'

networks:
  locust-network:
    name: locust-network
  lb-network:
    name: lb-network
    external: true

services:
  master:
    image: locust
    build: 
      context: .
      dockerfile: locust/Dockerfile
    ports:
     - "8089:8089"
    #  - "6565:6565"
    external_links:
      - lb:lb
    volumes:
      - /home/janus/personal/UCU/BachelorDegree/rsocket-performance-testing/:/locust/
    networks:
      - locust-network
      - lb-network
    command: >
      -f /locust/locust/locustfile.py
      --master -H http://${HOST}:8089
      --master-bind-host=${HOST}
      --master-bind-port=5557
      -u ${NUM_USERS}
      -r ${SPAWN_RATE}
      -t ${RUN_TIME}
      --csv /locust/results/${CSV_PREFIX}
      --csv-full-history
      --only-summary
      --autostart
      --autoquit 5
    # --headless
  
  worker:
    image: locust
    build: 
      context: .
      dockerfile: locust/Dockerfile
    volumes:
      - /home/janus/personal/UCU/BachelorDegree/rsocket-performance-testing/:/locust/
    # ports:
    #   - "5557:5557"
    external_links:
      - lb:lb
    links:
      - master:master
    networks:
      - locust-network
      - lb-network
    command: >
      -f /locust/locust/locustfile.py
      --worker
      --master-host=master
    depends_on:
      - "master"