version: '3'

networks:
  lb-network:
    name: lb-network
  lb-locust-network:
    name: lb-locust-network

services:
  lb:
    image: lb
    environment:
      - HOST=${HOST}
      - STRATEGY=${STRATEGY}
      - NUM_SERVERS=${NUM_SERVERS}
      - SERVERS_ADDRESSES=${SERVERS_ADDRESSES}
      - WORK_TYPE=${WORK_TYPE}
      - VARIATION_SCALE=${VARIATION_SCALE}
    build: 
      context: .
      dockerfile: lb/Dockerfile
      # target: lb/lb
    ports:
      - "6565:6565"
    expose:
      - 6565
    networks:
      - lb-network
      - lb-locust-network
    depends_on:
      - server1
      - server2
      - server3
    command: >
      python3 
      /build/lb/launch_lb.py 
      --strategy=$STRATEGY 
      --server_count=$NUM_SERVERS 

  
  server1:
    image: server
    build: 
      context: .
      dockerfile: lb/servers/Dockerfile
    environment:
      - HOST=${HOST}
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - lb-network
    ports:
      - "6566:6566"
    command: >
      python3
      lb/servers/launch_lb_servers.py
      --port=$SERVER_PORT
      --work_type=$WORK_TYPE
      --variation_scale=$VARIATION_SCALE
  
  server2:
    image: server
    build: 
      context: .
      dockerfile: lb/servers/Dockerfile
    environment:
      - HOST=${HOST}
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - lb-network
    ports:
      - "6567:6566"
    command: >
      python3
      lb/servers/launch_lb_servers.py
      --port=$SERVER_PORT
      --work_type=$WORK_TYPE
      --variation_scale=$VARIATION_SCALE
  
  server3:
    image: server
    build: 
      context: .
      dockerfile: lb/servers/Dockerfile
    environment:
      - HOST=${HOST}
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - lb-network
    # ports:
    #   - "6568:6566"
    command: >
      python3
      lb/servers/launch_lb_servers.py
      --port=$SERVER_PORT
      --work_type=$WORK_TYPE
      --variation_scale=$VARIATION_SCALE
    # bash
    # ind.sh 
    # &&
  
  # server:
  #   image: imageName
  #   deploy:
  #     mode: replicated

